"""empty message

Revision ID: 00cd06ff05ff
Revises: 5fd52ac14804
Create Date: 2021-07-06 11:14:48.400235

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '00cd06ff05ff'
down_revision = '5fd52ac14804'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('height', sa.Integer(), nullable=False))
    op.add_column('people', sa.Column('mass', sa.Integer(), nullable=False))
    op.add_column('people', sa.Column('hair_color', sa.String(), nullable=False))
    op.add_column('people', sa.Column('skin_color', sa.String(), nullable=False))
    op.add_column('people', sa.Column('eye_color', sa.String(), nullable=False))
    op.add_column('people', sa.Column('birth_year', sa.String(), nullable=False))
    op.add_column('people', sa.Column('gender', sa.String(), nullable=False))
    op.add_column('people', sa.Column('created', sa.DATE(), nullable=False))
    op.add_column('people', sa.Column('edited', sa.DATE(), nullable=False))
    op.add_column('people', sa.Column('name', sa.String(), nullable=False))
    op.add_column('people', sa.Column('ulr', sa.String(), nullable=False))
    op.drop_column('people', 'result')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('result', sqlite.JSON(), nullable=False))
    op.drop_column('people', 'ulr')
    op.drop_column('people', 'name')
    op.drop_column('people', 'edited')
    op.drop_column('people', 'created')
    op.drop_column('people', 'gender')
    op.drop_column('people', 'birth_year')
    op.drop_column('people', 'eye_color')
    op.drop_column('people', 'skin_color')
    op.drop_column('people', 'hair_color')
    op.drop_column('people', 'mass')
    op.drop_column('people', 'height')
    # ### end Alembic commands ###
