"""empty message

Revision ID: 057c8990a9eb
Revises: 
Create Date: 2021-08-06 00:19:45.103049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '057c8990a9eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('films',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('_id', sa.String(), nullable=False),
    sa.Column('_v', sa.String(), nullable=False),
    sa.Column('producer', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('director', sa.String(), nullable=False),
    sa.Column('release_date', sa.String(), nullable=False),
    sa.Column('opening_crawl', sa.String(), nullable=False),
    sa.Column('created', sa.DATE(), nullable=False),
    sa.Column('edited', sa.DATE(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ulr', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('people',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('_id', sa.String(), nullable=False),
    sa.Column('_v', sa.String(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('mass', sa.Integer(), nullable=False),
    sa.Column('hair_color', sa.String(), nullable=False),
    sa.Column('skin_color', sa.String(), nullable=False),
    sa.Column('eye_color', sa.String(), nullable=False),
    sa.Column('birth_year', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('created', sa.String(), nullable=False),
    sa.Column('edited', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('planets',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('_id', sa.String(), nullable=False),
    sa.Column('_v', sa.String(), nullable=False),
    sa.Column('diameter', sa.Integer(), nullable=False),
    sa.Column('rotation_period', sa.Integer(), nullable=False),
    sa.Column('orbital_period', sa.Integer(), nullable=False),
    sa.Column('gravity', sa.String(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('climate', sa.String(), nullable=False),
    sa.Column('terrain', sa.String(), nullable=False),
    sa.Column('surface_water', sa.Integer(), nullable=False),
    sa.Column('created', sa.String(), nullable=False),
    sa.Column('edited', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('species',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('_id', sa.String(), nullable=False),
    sa.Column('_v', sa.String(), nullable=False),
    sa.Column('classification', sa.String(), nullable=False),
    sa.Column('designation', sa.String(), nullable=False),
    sa.Column('average_height', sa.Integer(), nullable=False),
    sa.Column('average_lifespan', sa.String(), nullable=False),
    sa.Column('hair_color', sa.String(), nullable=False),
    sa.Column('skin_color', sa.String(), nullable=False),
    sa.Column('eye_color', sa.String(), nullable=False),
    sa.Column('lenguaje', sa.String(), nullable=False),
    sa.Column('created', sa.DATE(), nullable=False),
    sa.Column('edited', sa.DATE(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ulr', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('starships',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('_id', sa.String(), nullable=False),
    sa.Column('_v', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('starship_class', sa.String(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=False),
    sa.Column('cost_in_credits', sa.String(), nullable=False),
    sa.Column('length', sa.String(), nullable=False),
    sa.Column('crew', sa.String(), nullable=False),
    sa.Column('passengers', sa.String(), nullable=False),
    sa.Column('max_atmosphering_speed', sa.String(), nullable=False),
    sa.Column('hyperdrive_rating', sa.String(), nullable=False),
    sa.Column('MGLT', sa.String(), nullable=False),
    sa.Column('cargo_capacity', sa.String(), nullable=False),
    sa.Column('consumables', sa.String(), nullable=False),
    sa.Column('created', sa.DATE(), nullable=False),
    sa.Column('edited', sa.DATE(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ulr', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('_id', sa.String(), nullable=False),
    sa.Column('_v', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('vehicle_class', sa.String(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=False),
    sa.Column('cost_in_credits', sa.String(), nullable=False),
    sa.Column('length', sa.String(), nullable=False),
    sa.Column('crew', sa.String(), nullable=False),
    sa.Column('passengers', sa.String(), nullable=False),
    sa.Column('max_atmosphering_speed', sa.String(), nullable=False),
    sa.Column('cargo_capacity', sa.String(), nullable=False),
    sa.Column('consumables', sa.String(), nullable=False),
    sa.Column('created', sa.DATE(), nullable=False),
    sa.Column('edited', sa.DATE(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ulr', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('favorite_uid', sa.String(), nullable=False),
    sa.Column('favorite_class', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    op.drop_table('vehicles')
    op.drop_table('users')
    op.drop_table('starships')
    op.drop_table('species')
    op.drop_table('planets')
    op.drop_table('people')
    op.drop_table('films')
    # ### end Alembic commands ###
