"""empty message

Revision ID: 34959801c997
Revises: e938b8790812
Create Date: 2021-08-05 01:41:13.762440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34959801c997'
down_revision = 'e938b8790812'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=False))
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(), nullable=False))
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
