"""empty message

Revision ID: 4bc2902acdde
Revises: 
Create Date: 2021-07-05 21:21:30.549678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bc2902acdde'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('_id', sa.String(), nullable=False),
    sa.Column('_v', sa.String(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('people')
    # ### end Alembic commands ###
