"""empty message

Revision ID: 95107dde19e2
Revises: 59c9adb16af6
Create Date: 2021-07-07 15:18:14.138100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95107dde19e2'
down_revision = '59c9adb16af6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('url', sa.String(), nullable=False))
    op.drop_column('planets', 'ulr')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('ulr', sa.VARCHAR(), nullable=False))
    op.drop_column('planets', 'url')
    # ### end Alembic commands ###
